version: '3'
services:
  web:
    restart: always
    env_file:
      - ./.env
    build: ./
    command: >
      sh -c "python ./manage.py makemigrations &&
             python ./manage.py migrate &&
             python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"